### ISSUE TITLE
Credit support?

### ISSUE THREAD

**Issue by lgrkvst** [formancehq/ledger#372]
**Is your feature request related to a problem? Please describe.**
A way to represent negative amounts, i.e. deficiency of funds.

**Summary**
If the ledger is used to mirror real world accounts (shortage of) assets, it should support negatives.

**Solution proposal**
A "limit" attribute on accounts. The transaction engine would guarantee I don't exceed that limit (just like it currently guarantees the limit of 0).

**Additional context**
Credits would expand the ledger's realm of use-cases, to performing FX between currencies with double-entry book-keeping (which @world can provide in a sense, albeit at the cost of complexity), interest calculations and cash optimisation.

**Comment by quenbyako** [comment]
I think credits are not related to accounting in any way.

@lgrkvst Here is my idea how you can do it:

In contract of spending money from account, create `overdraft` directive with amount of credit limit for your transaction:

```
send [COIN 100] (
  source = @user allowing overdraft up to 500 // or 'allowing unbounded overdraft'
  destination = @store
)
```

Then, (@jdupas22 @flemzord @altitude correct me guys if i'm wrong please), ledger sending notifications about transactions via message queue. If you got a notification, that `@user`'s balance is negative, create a "credit agreement" with user, that they need to pay X coins per X months, to cover their credit using [scheduled payment](https://www.formance.com/use-cases-library/17371813). For example:

```
send [COIN 100] (
  source = @user:pending
  destination = @your_bank
)
set_tx_meta("payday", "2022-12-20")
```

Or something like this.

To be honest: i'm really newbie here, so i suck in writing contracts, but definitely what i can say that you can do this credits mechanics by yourself, ledger is already too complex as i can see in the source code, and currency conversions (really important feature) can't fit in existed system (because, like credit system, it is also such a complex shit)

@flemzord @altitude correct my answer and thought about credit feature, please, maybe i'm wrong about both of these parts 😉

**Comment by lgrkvst** [comment]
@quenbyako: Surely you could solve any use-case without the notion of negative balances. Depending on what you want to solve, the downside might be that the system becomes overly complex.

At the end of the day it's down to what product you're aiming to build, and that may be the issue at hand: I cannot picture a real-world use case where it makes sense to dictate overdraft at the tx level, nor an example where the account holder (sender) gets to choose whether to overdraft or not. On the contrary it introduces the kind of complexity that you're solving above by entering account holders into credit agreements after the fact that their account has already been overdrafted.

Credit should be an attribute at the account level.

@jdupas22: I agree checking should be done at tx time. Cron jobs are better suited for interest calculations.

Having that said, both FX and interest calculations are at least to me way beyond the scope of a ledger microservice.

**Comment by jdupas22** [comment]
Hey @quenbyako ! You're kind of right :) But usually i you'll want to use a specific pattern of numscript file for transaction that are "allowed" to generate overdrafts. So the solution would be like you said, listen to the ledger events and taking actions when some accounts go in negative. I think the "slippery slope" here is that this starts to be a bit too deep in the user's logic. The ledger in itself aims to be a generic but customizable solution. 
We can imagine a rule to subscribe to specific events (like creation of overdrafts) in the future though ! I'd be very interested in seeing this unfold. I'll discuss it with the team !

@lgrkvst Exactly, there is a lot of ways to solve most problems in the ledger currently, the flexibility of accounts makes it so that most can be solved simply by adding some steps to the payment flow, and sometimes a bit of backend actions for the user. 
However, i agree that the "credit" attribute should be set at the account level. That's something we're working on. We were not really happy about the design solution of the mapping we had at account level, so it's going to be iterated on in the near future. Obviously, the Numscript solution to define the overdraft at the transaction level is not perfect either, but it allows us to solve more immediate problems for some of our users, and to find the time to implements a better solution soon :)

Don't hesitate if you have any other question ! I'm also tagging @altitude here in case he has something to add !

**Comment by jdupas22** [comment]
Hey guys ! I'm going to close this issue since it seems not to be active anymore ! Don't hesitate to come talk with us at https://formance.com/slack if you have any question about it (or something else) !

I'll try to ping both of you once we have a better solution making its way into a PR ! :)
